


//assets
export const FETCH_ASSETS = 'FETCH_ASSETS'
export const FETCH_ASSETS_FUFILLED = 'FETCH_ASSETS_FUFILLED'
export const FETCH_ASSETS_FAILED =  "FETCH_ASSETS_FAILED"
export const ON_CHANGE_TEXT = 'ON_CHANGE_TEXT'

export const FETCH_DATA_TEST = 'MULTI_FETCH_DATA_TEST'
